[package]
name = "matt-thing"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[[bin]]
name = "matt-thing"
path = "src/main.rs"
doc = false

[dependencies]
hyper = "0.9.10"
serde_json = "0.8.1"
